services:
  - type: web
    name: my-first-app
    runtime: static
    env: static
    plan: free
    region: oregon
    buildCommand: ./build.sh
    staticPublishPath: ./build/web
    autoDeploy: true
    envVars:
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_KEY
        sync: false
